### ISSUE TITLE
ValueError: 'jacobian' in __slots__ conflicts with class variable

### ISSUE THREAD

**Issue by AlesAld** [elisepegg/py_bonemat_abaqus#2]
Hello Elise,

first of all, thank you very much for your great job. I would be intersted in extracting the density associated to each element of the mesh for statistical intenisty modelling purposes, and I bumped into your code. However, today I was trying to launch it, but even though I used the example files which were available, I got a number of warinings and in particular the error message I've pasted in the object. Do you have any clues about it? (I am pretty confident using Matlab, but less experienced as far as python is concerned) .

Here I paste the messages I get:

warnings.warn(msg)
Traceback (most recent call last):
  File "C:/Users/DIMEAS/PycharmProjects/pythonProject3/pip.py", line 1, in <module>
    import pip
  File "C:\Users\DIMEAS\PycharmProjects\pythonProject3\pip.py", line 6, in <module>
    from py_bonemat_abaqus.run import run
  File "C:\Users\DIMEAS\PycharmProjects\pythonProject3\venv\lib\site-packages\py_bonemat_abaqus\run.py", line 15, in <module>
    from py_bonemat_abaqus import general, data_import, calc, data_output
  File "C:\Users\DIMEAS\PycharmProjects\pythonProject3\venv\lib\site-packages\py_bonemat_abaqus\data_import.py", line 23, in <module>
    from py_bonemat_abaqus.classes import linear_tet, quad_tet, linear_wedge, linear_hex
  File "C:\Users\DIMEAS\PycharmProjects\pythonProject3\venv\lib\site-packages\py_bonemat_abaqus\classes.py", line 398, in <module>
    class linear_hex:
ValueError: 'jacobian' in __slots__ conflicts with class variable

Cheers,

Alessandra

**Comment by elisepegg** [comment]
Hi Alessandra,

So sorry to hear about this issue with the code. I'm not entirely sure where it is going wrong from the errors but I wonder if it relates to the python version you are using. I wrote the code a while ago and it works with Python 2, but if you try to run it using Python 3 you might well encounter difficulties (I haven't had the time to update the code).

It might also be worth investigating bonemat.org, as that's a better maintained freeware and should do the same thing.

I hope that helps,

Elise

________________________________

**Comment by DaStMPE** [comment]
Hello Elise and Alessandra,

first of all thank you very much for the very nice and helpful library Elise.
I ran into the same issues as Alessandra and after trying to adapt or move the library to python 3, I created a simple workaround for me by calling py_bonemat with a python 2.7 interpreter as subprocess of my python 3 script. Maybe this solution could also work for you Alessandra.

Best regards,
Daniel

**Comment by Trensicourt** [comment]
@DaStMPE 
Hi!
Would you perhaps mind sharing the scripting solution? I'm having issues creating the subprocess.

**Comment by Trensicourt** [comment]
I did it!
It only took me 4 hours, which felt like a life time, to get the code working.

**Comment by elisepegg** [comment]
Apologies for causing these issues with the out of date Python 2 syntax. I will endeavour to update the script to Python 3 as soon as possible. I notice there is now a python 3 version of pydicom so hopefully this will be fairly straight forward.

Best wishes,

Elise
